server:
  # PORT 설정
  port: 8088

spring:
  # DB 설정
  datasource:
    # 기본 설정
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/y2k?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    userName: yyk
    password: 1234

  devtools:
    # 저장 시, 자동 리로드
    livereload:
      enabled: true


  # 파일 전송 설정
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 30MB
      location: c:\Temp\upload


# mybatis 설정
mybatis:
  config-location: mybatis/mybatis-config.xml
  type-aliases-package: com.y2k
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true